### ISSUE TITLE
More detailed installation instructions please / mod structure is explained poorly (sorry)

### ISSUE THREAD

**Issue by samsunix** [JereKuusela/valheim-expand_world_music#1]
Steps taken;
- Installed Bepinex, Expand World Data and expand music mods.
- Created music folders with songs
`/steamapps/common/Valheim/BepInEx/config/expand_world/music/`, `SteamLibrary/steamapps/common/Valheim/BepInEx/config/music/`, `SteamLibrary/steamapps/common/Valheim/BepInEx/plugins/expand_world/music/`and
`SteamLibrary/steamapps/common/Valheim/BepInEx/plugins/music/`

Edit expand_music.yaml:

```
- name: respawn
  clips: []
  volume: 1
  fadeInTime: 3
  loop: true
- name: intro
  clips:
  - Entering Valheim
  volume: 0.5
  fadeInTime: 5
  alwaysFadeOut: true
- name: menu
  clips:
  - MenuMusic
  volume: 0.6
  fadeInTime: 2
  loop: true
- name: combat
  clips:
  - music/fight.mp3
  volume: 0.5
  fadeInTime: 10
  loop: true
```

Issue: 
- Songs do not appear with ew_musics command & not all songs seem to play. 

Please provide mod structure tree which is easy to follow.
Please provide detailed explanation how to setup songs for biomes etc. 
Please provide file size / length / format limitations if any.

**Comment by samsunix** [comment]
Narrowed down correct folder path:
/steamapps/common/Valheim/BepInEx/config/expand_world/music/

**Comment by samsunix** [comment]
it appears even vanilla game is not calling combat 

...does nothing:

```
- name: combat
  clips:
  - music/fight.mp3
  volume: 0.5
  fadeInTime: 3
  loop: true
```
